### ISSUE TITLE
Progress tracker

### ISSUE THREAD

**Issue by laymonage** [laymonage/giscussions#28]
This issue serves as a tracker for other issues that need to be resolved as we work towards 1.0 (do we even have versioning?). I'm currently listing these down so that I don't forget when I need to create separate issues later.

## Meta

- [x] Landing page and onboarding steps (#43)
- [x] Client script (#44)
- [x] Logo (#45)
- [x] Contributing guide (#46)

## Bugs/limitations

- [ ] Cannot show more than 100 replies (#32)
- [ ] Cannot toggle upvote (#31)

## New features

- [x] Automatic discussion creation if no matching discussion exists (#33)
- [x] Other methods to find a matching discussion (e.g. `discussionNumber`, `<title>`, `og:title`, etc.) (#34)
- [ ] Show/hide comment toggle for hidden comments and replies (#35)
- [ ] `KebabHorizontalIcon` menu (add copy link and quote reply options) (#36)
- [ ] New themes (#37)
- [ ] Support Q&A mode (if that makes sense?) (#38)
- [ ] Cover GFM edge cases/features (#47)

## Improvements

- [ ] Drop passthru GraphQL API when possible (#30)
- [ ] Replace `@peculiar/webcrypto` with built-in Node `crypto` module (#29)
- [ ] Improve error handling (#39)
- [ ] Drop unused CSS variables (#48)
- [ ] Audit security stuff (#40)
- [ ] Audit accessibility stuff (#42)
- [ ] Evaluate other data-fetching libraries (still in #32)
- [ ] Evaluate `@primer` and other GitHub stuff (CSS libraries, components, etc.) (#41)

**Comment by laymonage** [comment]
I think we no longer need this issue; we can track the progress in each issue.
